server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xdh-java/SpringClouds.git
          search-paths: config
          username: xdh211985@163.com
          password: XDHxdh123...
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/